### ISSUE TITLE
Mise en place de docker (compose)

### ISSUE THREAD

**Issue by TBoileau** [incentive-factory/iletaitunefoisundev#106]
- Container web (apache, nginx, caddy) pour l'API
- Front Node 16
- Container MySQL 8
- Back PHP >= 8.1
- Neo4j + Web UI
- ElasticSearch

**Comment by AlexandreGerault** [comment]
Si c'est pour de l'environnement de développement j'ai un truc comme ça:
https://github.com/AlexandreGerault/OpenClassrooms_Blog/blob/develop/docker-compose.yaml

Pour un container nginx et un container mysql. Par contre j'ai aussi php dans docker :innocent:

**Comment by TBoileau** [comment]
C'est vrai que j'ai oublié de préciser PHP

**Comment by n3wborn** [comment]
Je guettais la [PR de Qadadain](https://github.com/incentive-factory/iletaitunefoisundev/pull/152/files) mais plusieurs points peuvent être améliorés (et certains risquent de poser problème) IMO. On a l'opportunité de découper les services grace à Docker mais on trouve trop de choses au même endroit (serveur + php + node + composer) et certaines directives sont inutiles ou risquent d'être modifiées suivant l'environnement de dev/test.

Je pense que la conf d'Alexandre apportera plus de souplesse avec des containers plus lights. De plus, les variables d'env qui pourront dynamiser la configuration sont un vrai plus.

J'étais en train de modifier une conf que j'utilise régulièrement mais j'ai pas cet aspect dynamique qui risque de poser problème avec la conf donnée à doctrine comme dans [config/packages/dev/doctrine.yaml#L3](https://github.com/incentive-factory/iletaitunefoisundev/blob/develop/server/config/packages/dev/doctrine.yaml#L3). 

Si jamais il y a des points à modifier dans sa conf on pourra toujours y revenir (comme par ex [le flag :ro](https://github.com/AlexandreGerault/OpenClassrooms_Blog/blob/develop/docker-compose.yaml#L24) qui n'existe plus (et servait seulement sous Mac).
