### ISSUE TITLE
Optimisations Docker

### ISSUE THREAD

**Issue by TBoileau** [incentive-factory/iletaitunefoisundev#176]
- Un container pour le front
- Séparer le container PHP et Apache
- Si besoin replacer Apache par Nginx
- Modifier la Ci pour ne lancer que les containers nécessaire selon les stages
- Optimiser la CI pour mettre en cache une fois la conf de docker stable

**Comment by TBoileau** [comment]
Assign @Octowire

**Comment by Octowire** [comment]
Parfait je m'occupe de ça

**Comment by n3wborn** [comment]
Je pense que se serait mieux de supprimer les `container_name: *` 

- ils sont inutiles car ils peuvent être remplacés par le nom du service lorsqu'on veut les contacter. Par ex `docker-compose exec apache bash` ouvrira un shell dans le container apache (car docker sait faire la relation service<->container)

- ils posent problèmes lorsqu'on utilise deja les noms en question dans d'autres projets. Par ex, si j'ai un autre projet docker et qu'un service a aussi `container_name: apache`, je serai dans l'impossibilité de build le projet
