### ISSUE TITLE
Mot de passe oublié

### ISSUE THREAD

**Issue by TBoileau** [incentive-factory/iletaitunefoisundev#186]
> Cette feature est séparée en 2 actions : 
> - Effectuer une demande d'oubli de mot de passe
> - Réinitialisation du mot de passe

## Demande d'oubli de mot de passe
**Domain** : Security
**Endpoint** : /api/security/forgotten-password/request
**Method** : POST
**Input** : email (NotBlank, Email)
**Handler** : Génération d'un token unique (UUID) dans `forgottenPasswordToken`, persister les modifications, envoie de l'email
**Remarques** : 
Doit être noter comme `async` dans la configuration de `messenger`
Pour l'envoie de l'email, installer le composant `mailer`.
Pour la persistence, prévoir l'implémentation d'une méthode `update` dans `UserGateway`.
Dans un premier, paramétrer la variable d'environnement `MAILER_DSN` à `null://default`
Penser à ajouter une nouvelle propriété `forgottenPasswordToken` dans `User`, qui peut être `null`, et qui être initialisée à `null` par défaut.
**Tests** : 
- Intégration : UserRepository::update
- Unit
- Fonctionnel : penser à tester quand tout est bon, et en envoyant des données invalides.

## Réinitialisation du mot de passe
**Domain** : Security
**Endpoint** : /api/security/forgotten-password/{forgottenPasswordToken}/reset
**Method** : POST
**Input** : plainPassword (NotBlank, Regex `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/`)
**Handler** : passer la propriété `forgottenPasswordToken` à null, hasher le mot de passe, persister les modifications
**Remarques** : 
Il sera peut être nécessaire d'implémenter un contrôleur en plus de l'input et du handler. Se baser sur [FinishQuestController](server/src/Adventure/Controller/FinishQuestController.php)
**Tests** : 
- Unit
- Fonctionnel : penser à tester quand tout est bon, et en envoyant des données invalides.

**Comment by yalit** [comment]
@TBoileau comme dit sur Discord, je peux m'en occuper. Je commente pour que puisses m'y assigner 😉

**Comment by yalit** [comment]
@TBoileau pour la partie réinitialisation du mot de passe, ne pourrait-on pas mettre tout dans l'input (incluant le token) et avoir un endpoint tel que /api/security/forgotten-password/reset ?

et je rajouterais aussi l'email dans l'input pour récupérer le user via l'email (identifier) et comparer le token en db avec le token reçu... oui?

**Comment by yalit** [comment]
petit rajout, test rajouté pour vérifier le dispatch correct du Message RequestForgottenPasswordInput car async...

**Comment by yalit** [comment]
@TBoileau je me rends compte qu'il y a une issue à rajouter suite à celle-ci: c'est le design d'un mail correct... pour l'instant cela n'envoie qu'une simple ligne avec le token dedans... 

il faudrait styler cela un peu plus ;-)

Une fois que tu auras défini un style guideline, je veux bien implémenter l'email sans soucis
